const id = "announcing-dont-explode/index.md";
						const collection = "articles";
						const slug = "announcing-dont-explode";
						const body = "\r\nMy website goes a long way towards demonstrating my various passions but what might not be so clear is just how desperately I want to work in the game industry. Being a military spouse so far has prevented me from living near any game studios and I’m not getting any younger. Even before my daughter was born I knew I just couldn’t live with myself wondering what if. Doubly true since someday she will tell me her dreams and I intend to say, “Go for it, just like I did.”\r\n\r\nSo, now that I’ve spent 20 years working in print design, animation, programming and earning a degree in game art it’s time put up or give up.\r\n\r\nI knew building my own game is no simple task and biting off too big of a project would certainly prove too much so as a learning opportunity I chose to create a very simple game with the sole purpose of experiencing the entire cycle from planning to launching to support, promotion and general business.\r\n\r\nBeing a husband, a father and a provider are unimaginably rewarding but leave little more than an hour or two each night if I’m going to be good at any of those the next day. But I stuck with it over the last 5 months and finally have a proof of concept. There’s not much to show as I’ve focused on the code first but now that I’m on to the art phase I’m very excited to announce “Don’t Explode!”\r\n\r\nI’ll be keeping the games official page updated as I make progress and hope to have some screens very soon. A special thanks to my fellow polycounters and the regulars in the #unity3d IRC for their priceless teachings.\r\n[View the game page here](/dont-explode/).\r\n\r\n![Announcing Don’t Explode!](assets/rockets1.jpg)\r\n";
						const data = {title:"Announcing Don’t Explode!",image:{src:"/_astro/featured.036c99e2.png",width:1024,height:500,format:"png",orientation:void 0},date:new Date(1420848000000),tag:["Maya","Unity","C#","Photoshop","AdMob"]};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/stran/Documents/Work/joelstransky_com/src/content/articles/announcing-dont-explode/index.md",
							rawData: "\r\ntitle: Announcing Don’t Explode!\r\ndate: 2015-01-10\r\ndescription: # Add post description (optional)\r\nimage: 'assets/dont-explode/featured.png' # Add image post (optional)\r\ntag: [Maya, Unity, C#, Photoshop, AdMob] # add tag\r",
						};

export { _internal, body, collection, data, id, slug };
